config/routes.rb
Rails.application.routes.draw do
  get 'seconds/page'

  get 'pages/landing'

  post 'pages/save_user'
  
  root 'pages#landing'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    @users = User.all
  end

  def save_user
    User.create(nombre: params[:nombre], edad: params[:edad], email: params[:email] )
    redirect_to root_path
  end
end

app/controllers/seconds_controller.rb
class SecondsController < ApplicationController
  def page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/seconds_helper.rb
module SecondsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Preparacion</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="is-loading">
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/landing.html.erb
<h1>Matias Jara</h1>

<%= form_tag(pages_save_user_path, {class: "alt"}) do %>
<div class="row uniform">
  <div class="6u 12u$(xsmall)">
    <%= text_field_tag "nombre",nil, placeholder: "ingrese nombre" %>
  </div>
  <div class="6u$ 12u$(xsmall)">
    <%= text_field_tag "edad",nil, placeholder: "ingrese edad" %>
  </div>
  <div class="12u$">
    <%= email_field_tag "email",nil, placeholder: "ingrese email" %>
  </div>
  <div class="12u$">
    <ul class="actions fit">
      <li><%= submit_tag "Enviar", class:"button special fit" %></li>
    </ul>
  </div>
  <% end -%>
</div>

<h2>Usuarios</h2>

<div class="table-wrapper">
  <table class="alt">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>email</th>
        <th>edad</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.email %></td>
        <td><%= user.edad %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/seconds/page.html.erb
<h1>Segunda</h1>

app/views/shared/_footer.html.erb
</div>
<!-- Footer -->
					<footer id="footer">
						<section>
							<form method="post" action="#">
								<div class="field">
									<label for="name">Name</label>
									<input type="text" name="name" id="name" />
								</div>
								<div class="field">
									<label for="email">Email</label>
									<input type="text" name="email" id="email" />
								</div>
								<div class="field">
									<label for="message">Message</label>
									<textarea name="message" id="message" rows="3"></textarea>
								</div>
								<ul class="actions">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</form>
						</section>
						<section class="split contact">
							<section class="alt">
								<h3>Address</h3>
								<p>1234 Somewhere Road #87257<br />
								Nashville, TN 00000-0000</p>
							</section>
							<section>
								<h3>Phone</h3>
								<p><a href="#">(000) 000-0000</a></p>
							</section>
							<section>
								<h3>Email</h3>
								<p><a href="#">info@untitled.tld</a></p>
							</section>
							<section>
								<h3>Social</h3>
								<ul class="icons alt">
									<li><a href="#" class="icon alt fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon alt fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon alt fa-github"><span class="label">GitHub</span></a></li>
								</ul>
							</section>
						</section>
					</footer>

			</div>

app/views/shared/_header.html.erb
<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<a href="<%= root_path %>" class="logo">Massively</a>
					</header>

				<!-- Nav -->
					<nav id="nav">
						<ul class="links">
							<li><a href="<%= root_path %>">Principal</a></li>
							<li><a href="<%= seconds_page_path %>">Segunda</a></li>
						</ul>
						<ul class="icons">
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
						</ul>
					</nav>
<div id="main">